export const RECEIVE_BEER_SUCCESS = 'RECEIVE_BEER_SUCCESS'
export type RECEIVE_BEER_SUCCESS = typeof RECEIVE_BEER_SUCCESS

export const RECEIVE_BEER_FAILURE = 'RECEIVE_BEER_FAILURE'
export type RECEIVE_BEER_FAILURE = typeof RECEIVE_BEER_FAILURE

export const REQUEST_BEER = 'REQUEST_BEER'
export type REQUEST_BEER = typeof REQUEST_BEER

export const SET_SELECTED_BEER = 'SET_SELECTED_BEER'
export type SET_SELECTED_BEER = typeof SET_SELECTED_BEER
